# http://learningtensorflow.com/lesson4/

In [7]:
import tensorflow as tf

x = tf.placeholder("float", 3)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[ 2.  4.  6.]


In [10]:
import tensorflow as tf

x = tf.placeholder("float", [None, 3])
y = x * 2

with tf.Session() as session:
    x_data = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]
    result = session.run(y, feed_dict={x: x_data})
    print(result)


[[  2.   4.   6.]
 [  8.  10.  12.]
 [ 14.  16.  18.]]
